import {
  Roboto_Flex as Roboto,
} from 'next/font/google'

import './global.css';

export const metadata = {
  title: 'Welcome to impec-clean',
  description: 'Generated by create-nx-workspace',
};

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`relative ${roboto.className}`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
